"""lft white-box backend: dispatch + the byte-exact (residual-zero) recovery of
Linus Akesson's "A Mind Is Born", plus the token round-trip / measure.

"A Mind Is Born" is a ~254-byte algorithmic RSID: no note table, no patterns --
every frame is GENERATED by arithmetic on one CIA-timer-driven counter, and the
relocated player uses undocumented 6502 opcodes. The recovery is therefore pure
white-box (run the player under an illegal-opcode 6502, tap the SID shadow); the
"program" is the static image + boot seed, and render() regenerates the dump
byte-exact -- modulo the project's already-documented don't-care bits (PW-high
unused nibble; the reg23 filter-external bit), the same masks the dump validator
applies.

Two integration specifics this test pins:
  * the dump must be framed at the tune's CIA-IRQ period (~16422 cyc), NOT the
    19656-cycle PAL raster frame -- ``LftBackend.native_cpf`` carries this and
    ``recover_program``/``verify_residual`` honour it automatically;
  * the lft fingerprint must NOT mis-fire on the Hubbard/GoatTracker drivers.

The fixture (.sid + headlessvice-rendered dump) is acquired exactly like the
Monty/GoatTracker gates and is in ``GATE_FIXTURES`` so CI pre-renders + mounts
it (it is an RSID; the container renders it).
"""

import numpy as np
import pytest

from preframr_tokens import (
    CPF,
    VOCAB,
    ids_to_program,
    measure,
    program_to_ids,
    recover_program,
    render_program,
    verify_residual,
)
from preframr_tokens.bacc.backends import select_backend
from preframr_tokens.bacc.backends.lft import CIA_CPF, LftBackend
from preframr_tokens.bacc.sidemu import load_psid
from tests._dump_fixture import acquire

_AMB_REL = "MUSICIANS/L/Lft/A_Mind_Is_Born.sid"
_AMB_URL = "https://hvsc.brona.dk/HVSC/C64Music/MUSICIANS/L/Lft/A_Mind_Is_Born.sid"


class _GtPsid:
    """gt2reloc single-speed shape (play = init + 3): must NOT match lft."""

    load_addr = 0x1000
    init_addr = 0x1000
    play_addr = 0x1003
    data = bytes([0x4C, 0xA3, 0x10, 0x4C, 0xA7, 0x10]) + bytes(16)


class _MontyPsid:
    """Hubbard Monty shape (play != 0, no lft relocate signature)."""

    load_addr = 0x8000
    init_addr = 0x8000
    play_addr = 0x8012
    data = bytes(64)


class _IrqWrongLoad:
    """play=0 but loaded outside the lft $0800-$0900 image window."""

    load_addr = 0x1000
    init_addr = 0x1000
    play_addr = 0x0000
    data = bytes(64)


class _IrqNoSignature:
    """play=0, in the load window, but missing the relocate byte signature."""

    load_addr = 0x0801
    init_addr = 0x08B2
    play_addr = 0x0000
    data = bytes(256)


def test_lft_matches_only_its_own_signature():
    assert LftBackend().matches(_GtPsid()) is False  # play != 0
    assert LftBackend().matches(_MontyPsid()) is False  # play != 0
    assert LftBackend().matches(_IrqWrongLoad()) is False  # load out of window
    assert LftBackend().matches(_IrqNoSignature()) is False  # signature absent


def test_native_cpf_is_cia_not_raster():
    # The lft backend frames the dump at the CIA-IRQ period, not the PAL frame.
    assert LftBackend().native_cpf == CIA_CPF
    assert CIA_CPF != CPF


@pytest.fixture(scope="module")
def a_mind_is_born_paths():
    return acquire(_AMB_REL, _AMB_URL, subtune=1)


def test_select_backend_dispatches_lft(a_mind_is_born_paths):
    sid, _ = a_mind_is_born_paths
    psid = load_psid(sid)
    assert psid.play_addr == 0  # IRQ-driven, no PSID play vector
    assert select_backend(psid).name == "lft"
    # and the lft signature does NOT claim the other drivers' tunes
    assert select_backend(_GtPsid()).name == "goattracker"


def test_a_mind_is_born_residual_zero(a_mind_is_born_paths):
    """Byte-exact over the whole tune, modulo the documented don't-care bits.

    ``verify_residual`` auto-selects the lft backend, frames the dump at the
    CIA period (native_cpf), and compares under the backend's documented mask
    (PW-high unused nibble + reg23 filter-external bit) -- no stored correction,
    no new don't-care lane."""
    sid, dump = a_mind_is_born_paths
    assert verify_residual(
        sid, dump, CPF, subtune=0
    ), "lft backend is NOT residual-zero on A Mind Is Born"


def test_a_mind_is_born_is_pure_generator(a_mind_is_born_paths):
    """The recovered program is the static image + boot seed: 0 score events,
    0 instruments. The generator IS the ~254-byte image (extreme sparsity)."""
    sid, dump = a_mind_is_born_paths
    program = recover_program(sid, dump, CPF, subtune=0)
    assert program.driver == "lft"
    assert program.score == []
    assert program.instruments == []
    image = program.seed["image"]
    assert 200 <= len(image) <= 512  # the tiny program image
    brk, frames = measure(program)
    assert brk["total"] / frames < 0.2, (
        f"A Mind Is Born: {brk['total']} tokens / {frames} frames = "
        f"{brk['total'] / frames:.4f} tok/frame (expected extreme sparsity)"
    )


def test_a_mind_is_born_token_roundtrip(a_mind_is_born_paths):
    sid, dump = a_mind_is_born_paths
    program = recover_program(sid, dump, CPF, subtune=0)
    ids = program_to_ids(program)
    assert ids and all(0 <= t < VOCAB for t in ids)
    program2 = ids_to_program(ids, driver="lft")
    assert program2.driver == "lft"
    assert program2.seed["image"] == program.seed["image"]
    assert np.array_equal(render_program(program2), render_program(program))
