"""BACC program containers.

A recovered tune = a per-voice score (sparse note-on events) + pitch-invariant
instrument definitions + a small initial-state seed, rendered byte-exact by a
driver VM. The per-frame modulation (vibrato/pulse/porta/drums/skydive/arp +
envelope) is regenerated by the VM, never stored.
"""

from dataclasses import dataclass, field


@dataclass
class NoteOn:
    """A score event: a voice triggers a note at a frame."""

    frame: int
    voice: int
    note: int
    instr: int
    lnth: int  # duration (bits 0-4) + flags (bit5 sustain, bit6 append, bit7 2nd-byte)
    porta: int


@dataclass
class BaccProgram:
    """A driver-agnostic recovered program + its driver-specific payload."""

    driver: str
    nframes: int
    boot: list  # 25-register state of frame 0 (startup seed)
    instruments: list  # per-instrument byte tuples (BACC + timbre params)
    score: list  # list[NoteOn], frame-ordered
    seed: dict = field(default_factory=dict)  # per-voice initial state + scalars
    tables: dict = field(default_factory=dict)  # driver tables (note table, etc.)
