"""White-box backend for Linus Akesson (lft) algorithmic RSID players.

Target: "A Mind Is Born" (HVSC MUSICIANS/L/Lft) -- a ~254-byte, IRQ-driven
RSID with NO note-table/pattern/orderlist. The whole tune is GENERATED by
arithmetic on a single CIA-timer-driven counter; the "score" is the tiny static
seed embedded in the program image. The player relocates itself into zero page
and uses undocumented 6502 opcodes (LAX/ALR/AXS/SLO/SRE/ANC...).

Recovery is therefore *pure white-box*: the recovered BACC "program" is the
seed (the 254-byte image + the init state) and the VM = the relocated player
run under an accurate illegal-opcode 6502. render() re-executes it; there is no
per-lane stored trace. Residual = 0 (byte-exact) modulo the project's
documented don't-care bits (PW-high unused bits 4-7; reg23 filter-external bit).

IRQ-rate note: lft drives the tune from the CIA timer at the Kernal default
(~16422 cycles), NOT the PAL raster frame (19656). The dump must be framed at
that period (pass cpf=16422 to per_frame_state) or the counter binning skews.
"""

import numpy as np

from preframr_tokens.bacc.backends.base import DriverBackend
from preframr_tokens.bacc.illegal_mpu import MPU65ILL
from preframr_tokens.bacc.primitive import BaccProgram

SID_BASE = 0xD400
NREG = 25
TRAP = 0xEA7E  # Kernal IRQ-exit; the play handler JMPs here -> we stop
CIA_CPF = 16422.0  # measured lft CIA-IRQ period (cycles)
PW_HI = (3, 10, 17)  # documented don't-care upper-nibble lanes
DONTCARE = {23: 0xF7}  # reg23 bit3 (filter external input) -- inaudible, corpus-clear


class _Mem(list):
    """64K RAM that latches SID writes into a 32-byte shadow."""

    def __init__(self):
        super().__init__([0] * 0x10000)
        self.sid = [0] * 0x20

    def __setitem__(self, addr, val):
        if isinstance(addr, slice):
            return super().__setitem__(addr, val)
        v = val & 0xFF
        if SID_BASE <= addr < SID_BASE + 0x20:
            self.sid[addr - SID_BASE] = v
        return super().__setitem__(addr, v)


class LftBackend(DriverBackend):
    """Run-the-player white-box backend for lft's algorithmic RSID tunes."""

    name = "lft"
    native_cpf = CIA_CPF  # frame the dump at the tune's CIA-IRQ period, not the raster
    mask_state = staticmethod(lambda s: mask_dontcares(s))

    def matches(self, psid):
        # RSID, IRQ-driven (play=0), self-relocating tiny image into zero page.
        if psid.play_addr != 0:
            return False
        if not (0x0800 <= psid.load_addr <= 0x0900):
            return False
        # signature: init does SEI; LDA #$31; STA $0314 (IRQ vector low) then a
        # relocate loop LDX #$fd / LDA $0802,X / STA $02,X.
        img = psid.data
        return (
            b"\x78\xa9\x31\x8d\x14\x03" in img
            and b"\xa2\xfd\xbd\x02\x08\x95\x02" in img
        )

    # ---- white-box machine ----
    def _machine(self, psid):
        mem = _Mem()
        for i, byte in enumerate(psid.data):
            mem[psid.load_addr + i] = byte
        mem[0xDC04] = 0x00  # CIA timer read stub
        mpu = MPU65ILL(memory=mem)
        return mpu, mem

    def _init(self, mpu, mem, init_addr):
        mpu.a = mpu.x = mpu.y = 0
        mpu.sp = 0xFF
        mpu.p = 0x24
        mpu.pc = init_addr
        self._run_to(mpu, {0x00D2})  # stop at the CLI wait-loop the IRQ interrupts

    def _run_to(self, mpu, stops, max_steps=2_000_000):
        steps = 0
        while steps < max_steps:
            if mpu.pc in stops:
                return
            mpu.step()
            steps += 1
        raise RuntimeError(f"runaway at pc={mpu.pc:#06x}")

    def _play(self, mpu, mem):
        """Fake one CIA IRQ: push frame, jump to vector $0314, run to JMP $ea7e."""
        mpu.stPushWord(0x00D2)
        mpu.stPush(mpu.p)
        mpu.p |= mpu.INTERRUPT
        mpu.pc = mem[0x0314] | (mem[0x0315] << 8)
        self._run_to(mpu, {TRAP})
        return list(mem.sid[:NREG])

    def recover(self, psid, nframes, subtune):
        """The recovered program = the seed (image + init state). Generators are
        the player itself (re-run by render). No per-frame trace is stored."""
        mpu, mem = self._machine(psid)
        self._init(mpu, mem, psid.init_addr)
        boot = list(mem.sid[:NREG])
        prog = BaccProgram(
            driver=self.name,
            nframes=nframes,
            boot=boot,
            instruments=[],  # algorithmic: no note-table instruments
            score=[],  # algorithmic: no score events -- pure generator
            seed={
                "load_addr": psid.load_addr,
                "init_addr": psid.init_addr,
                "image": list(psid.data),  # the 254-byte program image = the seed
                "cia_cpf": CIA_CPF,
            },
        )
        return prog

    def render(self, program):
        """Re-run the player to regenerate every frame byte-exact.

        Frame 0 is the boot seed (the dump's pre-init frame, all-quiet); each
        subsequent frame is one faked CIA IRQ. This aligns the render 1:1 with
        the dump grid (render[f] == dump[f]), matching the other backends.
        """
        s = program.seed
        psid = _ImageStub(s["load_addr"], s["init_addr"], bytes(s["image"]))
        mpu, mem = self._machine(psid)
        self._init(mpu, mem, psid.init_addr)
        out = np.zeros((program.nframes, NREG), dtype=np.int64)
        out[0] = program.boot
        for f in range(1, program.nframes):
            out[f] = self._play(mpu, mem)
        return out


class _ImageStub:
    def __init__(self, load_addr, init_addr, data):
        self.load_addr = load_addr
        self.init_addr = init_addr
        self.data = data
        self.play_addr = 0


def mask_dontcares(state):
    """Apply the project's documented logging-convention masks in place-copy."""
    s = np.asarray(state).copy()
    for r in PW_HI:
        s[:, r] &= 0x0F
    for r, m in DONTCARE.items():
        s[:, r] &= m
    return s
