import pandas as pd

FRAME_REG = -128
DELAY_REG = -127
VOICE_REG = -126
RESERVED_REG_NEG124 = -124
RESERVED_REG_NEG123 = -123
PAD_REG = -1
FC_LO_REG = 21
FILTER_REG = 23

SET_OP = 0
DIFF_OP = 1
FLIP_OP = 3
TRANSPOSE_OP = 5
RESERVED_OP_7 = 7
DO_LOOP_OP = 16
SUBREG_FLUSH_OP = 18
PATTERN_REPLAY_OP = 22
PATTERN_OVERLAY_OP = 23
HARD_RESTART_OP = 25
LEGATO_OP_CLUSTER_2 = 28
LEGATO_OP_CLUSTER_3 = 29
LEGATO_OP_CLUSTER_4 = 30
LEGATO_OP_CLUSTER_7 = 31
RESERVED_OP_52 = 52
RESERVED_OP_53 = 53
SWEEP_OP = 64
INSTR_DEF_OP = 78
INSTR_STEP_OP = 79
INSTR_END_OP = 80
INSTR_REF_OP = 81
GEN_TRI_OP = 83
GEN_TUNING_OP = 84
GEN_TABLE_DEF_OP = 85
GEN_TABLE_STEP_OP = 86
GEN_TABLE_END_OP = 87
GEN_TABLE_REF_OP = 88

INSTR_OFF_CTRL = 4
INSTR_OFF_AD = 5
INSTR_OFF_SR = 6
INSTR_SUBREG_FRAME = 7

SWEEP_SUBREG_START_HI = 0
SWEEP_SUBREG_START_LO = 1
SWEEP_SUBREG_DELTA_HI = 2
SWEEP_SUBREG_DELTA_LO = 3
SWEEP_SUBREG_LEN = 4
SWEEP_SUBREG_PERIOD = 5
SWEEP_MIN_LEN = 4
SWEEP_MAX_SPAN = 17

GEN_TRI_SUBREG_START_HI = 0
GEN_TRI_SUBREG_START_LO = 1
GEN_TRI_SUBREG_STEP_HI = 2
GEN_TRI_SUBREG_STEP_LO = 3
GEN_TRI_SUBREG_LO_HI = 4
GEN_TRI_SUBREG_LO_LO = 5
GEN_TRI_SUBREG_HI_HI = 6
GEN_TRI_SUBREG_HI_LO = 7
GEN_TRI_SUBREG_DIR = 8
GEN_TRI_SUBREG_LEN = 9

GEN_TUNING_SUBREG_REF = 0

GEN_TABLE_SUBREG_PERIOD = 0
GEN_TABLE_SUBREG_MODE = 1
GEN_TABLE_SUBREG_BASE_NOTE = 2
GEN_TABLE_SUBREG_ABS_LO = 3
GEN_TABLE_SUBREG_ABS_HI = 4
GEN_TABLE_SUBREG_OFFSET = 5
GEN_TABLE_SUBREG_RESID_LO = 6
GEN_TABLE_SUBREG_RESID_HI = 7

GEN_TABLE_MODE_ABS = 0
GEN_TABLE_MODE_NOTE = 1

GEN_TABLE_REF_SUBREG_ID = 0
GEN_TABLE_REF_SUBREG_BASE_NOTE = 1
GEN_TABLE_REF_SUBREG_LEN_HI = 2
GEN_TABLE_REF_SUBREG_LEN_LO = 3

GEN_MAX_PERIOD = 24
GEN_MIN_TRI = 6
GEN_MAX_SPAN = 17
GEN_FREQ_REGS = (0, 7, 14)
GEN_SCALAR_REGS = (2, 9, 16, 21, 23, 24)

CODEBOOK_ID_VAL_OPS = frozenset(
    {
        INSTR_DEF_OP,
        INSTR_END_OP,
        INSTR_REF_OP,
    }
)
CODEBOOK_ID_OP_SUBREGS = frozenset(
    {
        (GEN_TABLE_REF_OP, GEN_TABLE_REF_SUBREG_ID),
    }
)


def is_codebook_id_atom(op, subreg):
    """True iff ``(op, subreg)``'s ``val`` is a tune-local codebook id (a define->ref
    pointer, NOT a magnitude) -- so it must never be value-snapped to a "nearest"
    alphabet entry (that silently rebinds the reference). ``CODEBOOK_ID_VAL_OPS`` carry
    the id in ``val`` for any subreg; ``CODEBOOK_ID_OP_SUBREGS`` only at the listed subreg.
    """
    return (
        int(op) in CODEBOOK_ID_VAL_OPS
        or (
            int(op),
            int(subreg),
        )
        in CODEBOOK_ID_OP_SUBREGS
    )


LOOP_OP_REG = -125

PATTERN_REPLAY_SUBREG_DIST_HI = 0
PATTERN_REPLAY_SUBREG_DIST_LO = 1
PATTERN_REPLAY_SUBREG_LEN = 2
PATTERN_REPLAY_SUBREG_OVERLAY_COUNT = 3
BACK_REF_DIST_LO_MASK = 0xFF
BACK_REF_DIST_HI_SHIFT = 8

PATTERN_OVERLAY_SUBREG_FRAME_OFFSET = 0
PATTERN_OVERLAY_SUBREG_TARGET_REG = 1
PATTERN_OVERLAY_SUBREG_NEW_VAL = 2

SLOPE_MAX_RUNTIME = 256

SLOPE_REG_TERMINAL_GRID = {
    0: 1,
    7: 1,
    14: 1,
    2: 32,
    9: 32,
    16: 32,
    21: 256,
}

TRAJ_REGS = (0, 2, 7, 9, 14, 16, 21)
FREQ_TRAJ_REGS = (0, 7, 14)

OSC_MAX_GAP = 2
OSC_MIN_ALTERNATION = 0.5
OSC_MIN_HALFCYCLES = 3


DIFF_PDTYPE = pd.UInt16Dtype()
IMPLIED_FRAME_REG = False
MAX_REG = 24
_MIN_DIFF = 32
MODE_VOL_REG = 24
MODEL_PDTYPE = pd.Int32Dtype()
PAD_ID = 0
REG_PDTYPE = pd.Int8Dtype()
TOKEN_KEYS = ["op", "reg", "subreg", "val"]
TOKEN_PDTYPE = pd.Int64Dtype()
UNICODE_BASE = 0x300
VAL_PDTYPE = pd.Int32Dtype()
SUBREG_PDTYPE = pd.Int16Dtype()
DESCRIPTION_PDTYPE = pd.Int8Dtype()
OP_PDTYPE = pd.UInt8Dtype()
IRQ_PDTYPE = pd.UInt16Dtype()
VOICES = 3
VOICE_REG_SIZE = 7
VOICE_CTRL_REG = {v: v * VOICE_REG_SIZE + 4 for v in range(VOICES)}

META_FREQ_BITS = 4
FILTER_BITS = 5
PCM_BITS = 5

LOSS_TIER_NAMES = ("structural", "mid", "content", "zero")

PAL_CLOCK = 17734475
DEFAULT_IRQ_CYCLES = 19656
TUNING_REF_HZ = 440
MIDI_N_TO_F = {n: (2 ** ((n - 69) / 12)) * TUNING_REF_HZ for n in range(128)}

DUMP_SUFFIX = r".dump.parquet"
UNI_SUFFIX = r".uni.zst"
PARSED_SUFFIX = r".[0-9]*.parquet"
