import pandas as pd

FRAME_REG = -128
DELAY_REG = -127
VOICE_REG = -126
RESERVED_REG_NEG124 = -124
RESERVED_REG_NEG123 = -123
PAD_REG = -1
FC_LO_REG = 21
FILTER_REG = 23

SET_OP = 0
DIFF_OP = 1
FLIP_OP = 3
TRANSPOSE_OP = 5
RESERVED_OP_7 = 7
DO_LOOP_OP = 16
SUBREG_FLUSH_OP = 18
PATTERN_REPLAY_OP = 22
PATTERN_OVERLAY_OP = 23
HARD_RESTART_OP = 25
LEGATO_OP_CLUSTER_2 = 28
LEGATO_OP_CLUSTER_3 = 29
LEGATO_OP_CLUSTER_4 = 30
LEGATO_OP_CLUSTER_7 = 31
PWM_PRESET_OP = 35
FC_PRESET_OP = 36
PWM_PRESET_SHIFTED_OP = 40
PWM_SUSTAIN_OP = 43
WAVETABLE_SUSTAIN_OP = 44
FREQ_TRAJ_OP = 45
TRACK_REF_OP = 46
RESERVED_OP_52 = 52
RESERVED_OP_53 = 53
SKEL_OP = 54
ORN_OP = 55
STAMP_DEF_OP = 56
STAMP_STEP_OP = 57
STAMP_END_OP = 58
STAMP_REF_OP = 59
STAMP_REL_REF_OP = 63
SWEEP_OP = 64
WAVETABLE_DEF_OP = 65
WAVETABLE_STEP_OP = 66
WAVETABLE_END_OP = 67
WAVETABLE_REF_OP = 68
WAVETABLE_ONESHOT_OP = 69
NOTE_OFF_OP = 71
NOTE_ON_OP = 75
GRADIENT_OP = 76
INIT_OP = 77
INSTR_DEF_OP = 78
INSTR_STEP_OP = 79
INSTR_END_OP = 80
INSTR_REF_OP = 81
GLOBAL_OSC_OP = 82

SKEL_SUBREG_INTERVAL = 0
SKEL_SUBREG_ABS = 1
ORN_SUBREG_TYPE = 0
ORN_SUBREG_P1 = 1
ORN_SUBREG_P2 = 2
ORN_SUBREG_HOLD = 3
ORN_TYPE_PLAIN = 0
ORN_TYPE_OCTAVE = 1
ORN_TYPE_ARP = 2
ORN_TYPE_SLIDE = 3
ORN_TYPE_VIB = 4
ORN_TYPE_RESID = 5
ORN_TYPE_HELD_ARP = 6
ORN_TYPE_SLIDE2 = 7
SLIDE2_MAX_DUR = 127
ARP_CYCLE_MAX_STEPS = 8
ARP_CYCLE_MIN_REPEAT = 2

STAMP_SUBREG_FRAME = 7
STAMP_CHAR_KICK = 0
STAMP_CHAR_TOM = 1
STAMP_CHAR_SNARE = 2
STAMP_CHAR_HAT = 3
STAMP_CHAR_CYMBAL = 4
STAMP_CHAR_NOISE_FX = 5
STAMP_CHAR_PITCH_FX = 6
STAMP_CHAR_OTHER = 7
STAMP_VOICE_REG_OFFSETS = (0, 2, 4, 5, 6)
STAMP_MINREP = 3
STAMP_REL_SUBREG_ID = 0
STAMP_REL_SUBREG_BASE_HI = 1
STAMP_REL_SUBREG_BASE_LO = 2

INSTR_OFF_CTRL = 4
INSTR_OFF_AD = 5
INSTR_OFF_SR = 6
INSTR_SUBREG_FRAME = STAMP_SUBREG_FRAME

SWEEP_SUBREG_START_HI = 0
SWEEP_SUBREG_START_LO = 1
SWEEP_SUBREG_DELTA_HI = 2
SWEEP_SUBREG_DELTA_LO = 3
SWEEP_SUBREG_LEN = 4
SWEEP_SUBREG_PERIOD = 5
SWEEP_MIN_LEN = 4
SWEEP_MAX_SPAN = 17

GRADIENT_MAX_STAGES = 8
GRADIENT_SUBREG_NSTAGES = 0
GRADIENT_SUBREG_END = 1
GRADIENT_SUBREG_VAL_BASE = 2
GRADIENT_SUBREG_DUR_BASE = GRADIENT_SUBREG_VAL_BASE + GRADIENT_MAX_STAGES
GRADIENT_MIN_STAGES = 3
GRADIENT_MAX_DUR = 256

GLOBAL_OSC_SUBREG_PERIOD = 0
GLOBAL_OSC_SUBREG_LEN = 1
GLOBAL_OSC_SUBREG_STATE_BASE = 2
GLOBAL_OSC_MIN_LEN = 4
GLOBAL_OSC_MAX_PERIOD = 8
GLOBAL_OSC_MAX_SPAN = 17
GLOBAL_OSC_REGS = (21, 22, 23, 24)

INIT_MAX_FRAMES = 64

WT_STEP_SUBREG_OFFSET = 0
WT_STEP_SUBREG_HOLD = 1
WT_STEP_SUBREG_LOOP = 2
WT_REF_SUBREG_ID = 0
WT_REF_SUBREG_LEN_HI = 1
WT_REF_SUBREG_LEN_LO = 2
WT_REF_SUBREG_LEAD = 3
WT_REF_SUBREG_LEADOFF = 4
WT_MINREP = 2
WT_SHORT_MAX = 4
WT_ONESHOT_SUBREG_LEN_HI = 0
WT_ONESHOT_SUBREG_LEN_LO = 1
WT_ONESHOT_SUBREG_OFFSET = 2
WT_ONESHOT_SUBREG_HOLD = 3
WT_ONESHOT_SUBREG_END = 4

CODEBOOK_ID_VAL_OPS = frozenset(
    {
        STAMP_DEF_OP,
        STAMP_END_OP,
        STAMP_REF_OP,
        WAVETABLE_DEF_OP,
        INSTR_DEF_OP,
        INSTR_END_OP,
        INSTR_REF_OP,
    }
)
CODEBOOK_ID_OP_SUBREGS = frozenset(
    {
        (STAMP_REL_REF_OP, STAMP_REL_SUBREG_ID),
        (WAVETABLE_REF_OP, WT_REF_SUBREG_ID),
    }
)


def is_codebook_id_atom(op, subreg):
    """True iff ``(op, subreg)``'s ``val`` is a tune-local codebook id (a define->ref
    pointer, NOT a magnitude) -- so it must never be value-snapped to a "nearest"
    alphabet entry (that silently rebinds the reference). ``CODEBOOK_ID_VAL_OPS`` carry
    the id in ``val`` for any subreg; ``CODEBOOK_ID_OP_SUBREGS`` only at the listed subreg.
    """
    return (
        int(op) in CODEBOOK_ID_VAL_OPS
        or (
            int(op),
            int(subreg),
        )
        in CODEBOOK_ID_OP_SUBREGS
    )


LOOP_OP_REG = -125

PATTERN_REPLAY_SUBREG_DIST_HI = 0
PATTERN_REPLAY_SUBREG_DIST_LO = 1
PATTERN_REPLAY_SUBREG_LEN = 2
PATTERN_REPLAY_SUBREG_OVERLAY_COUNT = 3
BACK_REF_DIST_LO_MASK = 0xFF
BACK_REF_DIST_HI_SHIFT = 8

PATTERN_OVERLAY_SUBREG_FRAME_OFFSET = 0
PATTERN_OVERLAY_SUBREG_TARGET_REG = 1
PATTERN_OVERLAY_SUBREG_NEW_VAL = 2

SLOPE_MAX_RUNTIME = 256

SLOPE_REG_TERMINAL_GRID = {
    0: 1,
    7: 1,
    14: 1,
    2: 32,
    9: 32,
    16: 32,
    21: 256,
}

TRAJ_REGS = (0, 2, 7, 9, 14, 16, 21)
FREQ_TRAJ_REGS = (0, 7, 14)

FT_SUBTYPE_MONOTONE_RAMP = 0
FT_SUBTYPE_OSCILLATE = 1
FT_SUBTYPE_RUN = 2
FT_SUBTYPE_MASK = 0x03
FT_PERIODIC_BIT = 0x04
FT_V0_INTERVAL_BIT = 0x08

FT_SUBREG_FLAGS = 0
FT_SUBREG_V0_HI = 1
FT_SUBREG_V0_LO = 2
FT_SUBREG_COUNT_HI = 3
FT_SUBREG_COUNT_LO = 4
FT_SUBREG_PERIOD = 5
FT_SUBREG_DELTA = 6
FT_SUBREG_TERMINAL_HI = FT_SUBREG_V0_HI
FT_SUBREG_TERMINAL_LO = FT_SUBREG_V0_LO
FT_SUBREG_RUNTIME = FT_SUBREG_COUNT_HI

FT_DELTA_ESCAPE = 0x80
FT_DELTA_MAX = 127
FT_MAX_PERIOD = 8

OSC_MAX_GAP = 2
OSC_MIN_ALTERNATION = 0.5
OSC_MIN_HALFCYCLES = 3


TRACK_REF_SUBREG_LEAD = 0
TRACK_REF_SUBREG_INTERVAL = 1
TRACK_REF_SUBREG_DETUNE = 2
TRACK_REF_SUBREG_DURATION = 3
TRACK_REF_SUBREG_COUNT = 4
TRACK_MIN_DURATION = 10
TRACK_MAX_DURATION = 255
TRACK_INTERVAL_RATIOS = (
    1.0,
    1.06,
    1.12,
    1.19,
    1.26,
    1.33,
    1.41,
    1.50,
    1.59,
    1.68,
    1.78,
    1.89,
    2.0,
    3.0,
    4.0,
    1.0,
)

PWM_PRESET_TABLE = tuple(range(0, 4096, 64))
FC_PRESET_TABLE = tuple(range(0, 65536, 256))

PWM_PRESET_VAL_TO_ID = {v: i for i, v in enumerate(PWM_PRESET_TABLE)}
FC_PRESET_VAL_TO_ID = {v: i for i, v in enumerate(FC_PRESET_TABLE)}

PRESET_REG_TO_OP = {
    2: PWM_PRESET_OP,
    9: PWM_PRESET_OP,
    16: PWM_PRESET_OP,
    21: FC_PRESET_OP,
}
PRESET_OPS = (PWM_PRESET_OP, FC_PRESET_OP)
PRESET_SHIFTED_OPS = (PWM_PRESET_SHIFTED_OP,)
PRESET_REG_GRID = {
    2: 64,
    9: 64,
    16: 64,
    21: 256,
}

SHIFTED_TO_BASE_OP = {
    PWM_PRESET_SHIFTED_OP: PWM_PRESET_OP,
}
BASE_TO_SHIFTED_OP = {v: k for k, v in SHIFTED_TO_BASE_OP.items()}
SHIFTED_OPS = tuple(SHIFTED_TO_BASE_OP.keys())

DIFF_PDTYPE = pd.UInt16Dtype()
IMPLIED_FRAME_REG = False
MAX_REG = 24
_MIN_DIFF = 32
MODE_VOL_REG = 24
MODEL_PDTYPE = pd.Int32Dtype()
PAD_ID = 0
REG_PDTYPE = pd.Int8Dtype()
TOKEN_KEYS = ["op", "reg", "subreg", "val"]
TOKEN_PDTYPE = pd.Int64Dtype()
UNICODE_BASE = 0x300
VAL_PDTYPE = pd.Int32Dtype()
SUBREG_PDTYPE = pd.Int16Dtype()
DESCRIPTION_PDTYPE = pd.Int8Dtype()
OP_PDTYPE = pd.UInt8Dtype()
IRQ_PDTYPE = pd.UInt16Dtype()
VOICES = 3
VOICE_REG_SIZE = 7
VOICE_CTRL_REG = {v: v * VOICE_REG_SIZE + 4 for v in range(VOICES)}

META_FREQ_BITS = 4
FILTER_BITS = 5
PCM_BITS = 5

LOSS_TIER_NAMES = ("structural", "mid", "content", "zero")

PAL_CLOCK = 17734475
DEFAULT_IRQ_CYCLES = 19656
TUNING_REF_HZ = 440
MIDI_N_TO_F = {n: (2 ** ((n - 69) / 12)) * TUNING_REF_HZ for n in range(128)}

DUMP_SUFFIX = r".dump.parquet"
UNI_SUFFIX = r".uni.zst"
PARSED_SUFFIX = r".[0-9]*.parquet"
